collector:
  kafka:
    producer:
      properties:
        "bootstrap-servers": localhost:9092
      topics:
        sensor-events: telemetry.sensor.v1
        hubs-events: telemetry.hubs.v1

grpc:
  client:
    echo:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext